### PR TITLE
add fluid craft support

### PR DESCRIPTION
**Pull request by asdflj**
add fluid craft support
动画

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11118

### CODE REVIEW

**Comment by asdflj** [comment]
@GlodBlock 
image

**Comment by GlodBlock** [comment]
does this conflict with fc's own recipe transfer?

**Comment by asdflj** [comment]
> 



> does this conflict with fc's own recipe transfer?

nope

**Comment by asdflj** [comment]
咋回事啊，构建不成功@Glodblok

**Comment by GlodBlock** [comment]
> 
你有我qq吗

**Comment by GlodBlock** [comment]
> 
> 没

1356392126

**Pull request merged**
