### PR TITLE
fix crash when using nei to fill pattern in pattern terminal without ae2fc

### PR DESCRIPTION
**Pull request by asdflj**
fix crash when using nei to fill pattern in pattern terminal without ae2fc

### CODE REVIEW

**Comment by glowredman** [comment]
I don't understand what you mean. Please use a translator (e.g. https://www.deepl.com/translator) if you have trouble with English.

**Comment by asdflj** [comment]
> I don't understand what you mean. Please use a translator (e.g. https://www.deepl.com/translator) if you have trouble with English.

Fix forget to install fluid craft,from the nei to fill ae2 pattern terminal well be crash

**Comment by Glease** [comment]
Do you mean "if player do not install ae2fc, filling from ae2 pattern terminal by clicking ? button in NEI screen will lead to crash"?

**Comment by asdflj** [comment]
> Do you mean "if player do not install ae2fc, filling from ae2 pattern terminal by clicking ? button in NEI screen will lead to crash"?

yeah

**Review by miozune — APPROVED** [review]

**Pull request merged**
